linters:
  enable-all: true
  disable:
    # deprecated
    - tenv

    - err113
    - testpackage
    - wrapcheck

linters-settings:
  gci:
    sections:
      - standard
      - default
      - localmodule

  varnamelen:
    ignore-names:
      - fn
      - v
    ignore-decls:

  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: github.com/pkg/errors

issues:
  exclude-rules:
    - source: "(noinspection|TODO)"
      linters: [ godot ]
    - path: "_test\\.go"
      linters:
        - err113
        - dupl
        - gosec
        - asasalint
